/**
 * Local data service: read countries, metro line lists, and line geometry from public/data.
 * Data is generated by scripts/download-data.ts.
 */

import type { FeatureCollection } from 'geojson';
import type { MetroLine } from '../types';

const DATA_BASE = '/data';

/** Convert country name to file key, e.g. "United Kingdom" -> "United_Kingdom" */
export function countryToKey(name: string): string {
  return String(name).replace(/\s+/g, '_');
}

/** Normalize country to display name: "South_Korea" -> "South Korea" */
function normalizeCountryName(name: string): string {
  return String(name).replace(/_/g, ' ').trim();
}

/** Get list of countries that have local data. Deduplicated by normalized name (e.g. only "South Korea", not "South_Korea"). */
export async function getCountries(): Promise<string[]> {
  const res = await fetch(`${DATA_BASE}/countries.json`);
  if (!res.ok) throw new Error('Local data not ready. Run npm run download-data first.');
  const list = (await res.json()) as unknown;
  const arr = Array.isArray(list) ? (list as string[]) : [];
  const seen = new Set<string>();
  const result: string[] = [];
  for (const name of arr) {
    const normalized = normalizeCountryName(name);
    if (normalized && !seen.has(normalized)) {
      seen.add(normalized);
      result.push(normalized);
    }
  }
  return result.sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }));
}

/** Get metro line list for a country from local file. */
export async function getLinesByCountry(countryName: string): Promise<MetroLine[]> {
  const key = countryToKey(countryName);
  const res = await fetch(`${DATA_BASE}/lines/${key}.json`);
  if (!res.ok) {
    if (res.status === 404) return [];
    throw new Error(`Failed to load lines list: ${res.status}`);
  }
  const list = (await res.json()) as unknown;
  return Array.isArray(list) ? (list as MetroLine[]) : [];
}

/** Get line geometry by relation ID from local file. */
export async function getLineGeometry(relationId: number): Promise<FeatureCollection> {
  const res = await fetch(`${DATA_BASE}/geometry/${relationId}.json`);
  if (!res.ok) {
    if (res.status === 404) throw new Error(`No local geometry for line ID ${relationId}`);
    throw new Error(`Failed to load geometry: ${res.status}`);
  }
  return res.json() as Promise<FeatureCollection>;
}
